quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quotesapp.urls')),
    path('users/', include('users.urls')),
]

quotes/quotesapp/urls.py
from django.urls import path
from . import views

app_name = 'quotesapp'

urlpatterns = [
    path('', views.main, name='root'),
    path('<int:page>', views.main, name='root_paginate'),
    path('tag/', views.tag, name='tag'),
    path('quote/', views.quote, name='quote'),
    path('author/', views.author, name='author'),
    path('detail/<int:author_id>', views.detail, name='detail'),
]

quotes/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

quotes/quotesapp/models.py
from django.db import models


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=100, null=False, unique=True)

    def __str__(self):
        return f"{self.name}"


class Author(models.Model):
    fullname = models.CharField(max_length=250)
    born_date = models.CharField(max_length=250)
    born_location = models.CharField(max_length=250)
    description = models.TextField()

    def __str__(self):
        return f"{self.fullname}"


class Quotes(models.Model):
    quote = models.TextField()
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, default=None, null=True)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f"{self.quote}"

quotes/users/models.py
from django.db import models

# Create your models here.

quotes/quotesapp/forms.py
from django.forms import ModelForm, CharField, TextInput, DateField, DateInput
from .models import Tag, Quotes, Author


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']


class QuotesForm(ModelForm):

    quote = CharField(min_length=10, max_length=150, required=True, widget=TextInput())

    class Meta:
        model = Quotes
        fields = ['quote']
        exclude = ['author', 'tags']


class AuthorForm(ModelForm):

    fullname = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    born_date = DateField(required=True, widget=DateInput(attrs={'type': 'date'}))
    born_location = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
    description = CharField(min_length=10, max_length=1000, required=True, widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

quotes/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

quotes/quotesapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TagForm, QuotesForm, AuthorForm
from .models import Tag, Author, Quotes
from .utils import get_mongodb
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

# db = get_mongodb()
# Create your views here.


def main(request, page=1):
    # quotes = Quotes.objects.all()
    # db = get_mongodb()
    # quotes = db.quotes.find()
    quotes = Quotes.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotesapp/index.html', {"quotes": quotes_on_page})


def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:root')
        else:
            return render(request, 'quotesapp/tag.html', {'form': form})

    return render(request, 'quotesapp/tag.html', {'form': TagForm()})


@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:root')
        else:
            return render(request, 'quotesapp/author.html', {'form': form})

    return render(request, 'quotesapp/author.html', {'form': AuthorForm()})


@login_required
def quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuotesForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            choice_tags = Tag.objects.filter(
                name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            choice_author_ids = request.POST.getlist('authors')
            for author_id in choice_author_ids:
                author = Author.objects.get(fullname=author_id)
                id = author.id
                new_quote.author_id = id
            new_quote = form.save()
            return redirect(to='quotesapp:root')
        else:
            return render(request, 'quotesapp/quote.html', {"tags": tags, 'form': form, "authors": authors})

    return render(request, 'quotesapp/quote.html', {"tags": tags, "authors": authors, 'form': QuotesForm()})


def detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quotesapp/detail.html', {"author": author})

quotes/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import RegisterForm, LoginForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotesapp:root')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:root')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})

def loginuser(request):
    if request.user.is_authenticated:
       return redirect(to='quotesapp:root')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotesapp:root')

    return render(request, 'users/login.html', context={"form": LoginForm()})

@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotesapp:root')

quotes/quotesapp/templates/quotesapp/author.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label for="id_fullname">Enter the author full name:</label>
        {{ form.fullname }}
        <span class="text-danger">{{ form.fullname.errors }}</span>
    </div>
    <div style="padding: 10px">
        <label for="id_born_date">Enter the author's date of birth:</label>
        {{ form.born_date }}
        <span class="text-danger">{{ form.born_date.errors }}</span>
    </div>
    <div style="padding: 10px">
        <label for="id_born_location">Enter the author's place of birth:</label>
        {{ form.born_location }}
        <span class="text-danger">{{ form.born_location.errors }}</span>
    </div>
    <div style="padding: 10px">
        <label for="id_description">Enter the author description:</label>
        {{ form.description }}
        <span class="text-danger">{{ form.description.errors }}</span>
    </div>
    <div class="grid">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quotesapp/templates/quotesapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <title>Quotes to Scrape</title>
    <link rel="stylesheet" href="{% static 'quotesapp/style.css' %}">
</head>

<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                {% if user.is_authenticated %}
                <ul>
                    <li>Welcome <b>{{ user.username }}!</b>
                        <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                    </li>
                </ul>
                {% else %}
                <ul>
                    <a href="{% url 'users:signup' %}" class="btn btn-primary">SignUp</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                </ul>
                {% endif %}
            </div>
        </div>

        {% block content %} {% endblock %}
</body>

</html>

quotes/quotesapp/templates/quotesapp/detail.html
{% extends "quotesapp/base.html" %}

{% block content %}

<div class="author-details">
    <h3 class="author-title">{{ author.fullname }}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{ author.born_date }}</span> <span
            class="author-born-location">
            {{ author.born_location }}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{ author.description }}
    </div>
</div>

{% endblock %}

quotes/quotesapp/templates/quotesapp/index.html
{% extends "quotesapp/base.html" %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            {% if user.is_authenticated %}
            <ul>
                <a href="{% url 'quotesapp:author' %}" class="btn btn-primary">Add Author</a>
                <a href="{% url 'quotesapp:quote' %}" class="btn btn-primary">Add Quote</a>
            </ul>
            {% else %}
            <ul>
            </ul>
            {% endif %}
        </nav>

        {% for quote in quotes %}

        <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{ quote.quote }}
                <span>
                    <div> by <small class="author" itemprop="author">{{quote.author}}</small>
                        <a href="{% url 'quotesapp:detail' quote.author.pk %}">(about)</a>
                    </div>
                </span>
                <div class="tags">
                    Tags:
                    {% if quote.tags.exists %}
                    {% for tag in quote.tags.all %}
                    <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
                    {% endfor %}
                    {% else %}
                    {% endif %}
                </div>
        </div>

        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                        href="{% if quotes.has_previous %} {% url 'quotesapp:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>


                <li class="next">
                    <a class='{% if not quotes.has_next %} disabled {% endif %}'
                        href="{% if quotes.has_next %} {% url 'quotesapp:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
    </div>

</div>

{% endblock %}
</main>
</body>

</html>

quotes/quotesapp/templates/quotesapp/quote.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Enter the quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            <select name="authors" required>
                {% for author in authors %}
                <option value="{{ author.fullname }}">{{ author.fullname }}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{ tag.name }}">{{ tag.name }}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit" name="quote_form_submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quotesapp/templates/quotesapp/tag.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/users/templates/users/login.html
{% extends "quotesapp/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <p><label> Username:
                {{ form.username }}
            </label></p>

    </div>

    <div>
        <p><label>Password:
                {{ form.password }}
            </label></p>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/users/templates/users/signup.html
{% extends "quotesapp/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <p><label> Password:
                {{ form.password1 }}
            </label>
            <span>{{ form.errors.password1 }}</span>
        </p>
    </div>
    <div>
        <p><label> Password confirmation:
                {{ form.password2 }}
            </label>
            <span>{{ form.errors.password2 }}</span>
        </p>
    </div>
    <div class="grid">
        <button type="submit mb-3">Submit</button>
        <button type="reset mb-3" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}